//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.225
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Chicken.Resources {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Chicken.Resources.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 API设置 的本地化字符串。
        /// </summary>
        public static string APISettingsPage_Header {
            get {
                return ResourceManager.GetString("APISettingsPage_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 编辑个人资料 的本地化字符串。
        /// </summary>
        public static string EditMyProfilePage_Header {
            get {
                return ResourceManager.GetString("EditMyProfilePage_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 你好世界 的本地化字符串。
        /// </summary>
        public static string HelloWorld {
            get {
                return ResourceManager.GetString("HelloWorld", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 对话 的本地化字符串。
        /// </summary>
        public static string NewMessagePage_Header {
            get {
                return ResourceManager.GetString("NewMessagePage_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 与{0}的对话 的本地化字符串。
        /// </summary>
        public static string NewMessagePage_Header_ChatWithUser {
            get {
                return ResourceManager.GetString("NewMessagePage_Header_ChatWithUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用户名格式不正确 的本地化字符串。
        /// </summary>
        public static string NewMessagePage_Header_NotAValidUserName {
            get {
                return ResourceManager.GetString("NewMessagePage_Header_NotAValidUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0}没有关注你 的本地化字符串。
        /// </summary>
        public static string NewMessagePage_Header_UserNotFollowYou {
            get {
                return ResourceManager.GetString("NewMessagePage_Header_UserNotFollowYou", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 提到: {0} 的本地化字符串。
        /// </summary>
        public static string NewTweetPage_Header_Mention {
            get {
                return ResourceManager.GetString("NewTweetPage_Header_Mention", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 引用: 的本地化字符串。
        /// </summary>
        public static string NewTweetPage_Header_Quote {
            get {
                return ResourceManager.GetString("NewTweetPage_Header_Quote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 回复: {0} 的本地化字符串。
        /// </summary>
        public static string NewTweetPage_Header_ReplyTo {
            get {
                return ResourceManager.GetString("NewTweetPage_Header_ReplyTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 怎么啦? 的本地化字符串。
        /// </summary>
        public static string NewTweetPage_Header_WhatsHappening {
            get {
                return ResourceManager.GetString("NewTweetPage_Header_WhatsHappening", resourceCulture);
            }
        }
    }
}
