//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.225
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Chicken.Resources {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Chicken.Resources.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 API类型: 的本地化字符串。
        /// </summary>
        public static string APISettingsPage_APIType {
            get {
                return ResourceManager.GetString("APISettingsPage_APIType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 链接: 的本地化字符串。
        /// </summary>
        public static string APISettingsPage_APIUrl {
            get {
                return ResourceManager.GetString("APISettingsPage_APIUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 API设置 的本地化字符串。
        /// </summary>
        public static string APISettingsPage_Header {
            get {
                return ResourceManager.GetString("APISettingsPage_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 底部 的本地化字符串。
        /// </summary>
        public static string AppBarButton_Bottom {
            get {
                return ResourceManager.GetString("AppBarButton_Bottom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 删除 的本地化字符串。
        /// </summary>
        public static string AppBarButton_Delete {
            get {
                return ResourceManager.GetString("AppBarButton_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 编辑 的本地化字符串。
        /// </summary>
        public static string AppBarButton_Edit {
            get {
                return ResourceManager.GetString("AppBarButton_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 表情 的本地化字符串。
        /// </summary>
        public static string AppBarButton_Emotion {
            get {
                return ResourceManager.GetString("AppBarButton_Emotion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 收藏 的本地化字符串。
        /// </summary>
        public static string AppBarButton_Favorite {
            get {
                return ResourceManager.GetString("AppBarButton_Favorite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 关注 的本地化字符串。
        /// </summary>
        public static string AppBarButton_Follow {
            get {
                return ResourceManager.GetString("AppBarButton_Follow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 提及 的本地化字符串。
        /// </summary>
        public static string AppBarButton_Mention {
            get {
                return ResourceManager.GetString("AppBarButton_Mention", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 私信 的本地化字符串。
        /// </summary>
        public static string AppBarButton_Message {
            get {
                return ResourceManager.GetString("AppBarButton_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 自己 的本地化字符串。
        /// </summary>
        public static string AppBarButton_MyProfile {
            get {
                return ResourceManager.GetString("AppBarButton_MyProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 引用 的本地化字符串。
        /// </summary>
        public static string AppBarButton_Quote {
            get {
                return ResourceManager.GetString("AppBarButton_Quote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 刷新 的本地化字符串。
        /// </summary>
        public static string AppBarButton_Refresh {
            get {
                return ResourceManager.GetString("AppBarButton_Refresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 回复 的本地化字符串。
        /// </summary>
        public static string AppBarButton_Reply {
            get {
                return ResourceManager.GetString("AppBarButton_Reply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 转推 的本地化字符串。
        /// </summary>
        public static string AppBarButton_Retweet {
            get {
                return ResourceManager.GetString("AppBarButton_Retweet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 保存 的本地化字符串。
        /// </summary>
        public static string AppBarButton_Save {
            get {
                return ResourceManager.GetString("AppBarButton_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 搜索 的本地化字符串。
        /// </summary>
        public static string AppBarButton_Search {
            get {
                return ResourceManager.GetString("AppBarButton_Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 发送 的本地化字符串。
        /// </summary>
        public static string AppBarButton_Send {
            get {
                return ResourceManager.GetString("AppBarButton_Send", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设置 的本地化字符串。
        /// </summary>
        public static string AppBarButton_Settings {
            get {
                return ResourceManager.GetString("AppBarButton_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 文字 的本地化字符串。
        /// </summary>
        public static string AppBarButton_Text {
            get {
                return ResourceManager.GetString("AppBarButton_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 顶部 的本地化字符串。
        /// </summary>
        public static string AppBarButton_Top {
            get {
                return ResourceManager.GetString("AppBarButton_Top", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 推文 的本地化字符串。
        /// </summary>
        public static string AppBarButton_Tweet {
            get {
                return ResourceManager.GetString("AppBarButton_Tweet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 取消关注 的本地化字符串。
        /// </summary>
        public static string AppBarButton_UnFollow {
            get {
                return ResourceManager.GetString("AppBarButton_UnFollow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 TWIP 4(O模式) 的本地化字符串。
        /// </summary>
        public static string Default_API_TWIP4 {
            get {
                return ResourceManager.GetString("Default_API_TWIP4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 English 的本地化字符串。
        /// </summary>
        public static string Default_Language_EN_US {
            get {
                return ResourceManager.GetString("Default_Language_EN_US", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 简体中文 的本地化字符串。
        /// </summary>
        public static string Default_Language_ZH_CN {
            get {
                return ResourceManager.GetString("Default_Language_ZH_CN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 简介: 的本地化字符串。
        /// </summary>
        public static string EditMyProfilePage_Description {
            get {
                return ResourceManager.GetString("EditMyProfilePage_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 编辑个人资料 的本地化字符串。
        /// </summary>
        public static string EditMyProfilePage_Header {
            get {
                return ResourceManager.GetString("EditMyProfilePage_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 链接: 的本地化字符串。
        /// </summary>
        public static string EditMyProfilePage_Link {
            get {
                return ResourceManager.GetString("EditMyProfilePage_Link", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 位置: 的本地化字符串。
        /// </summary>
        public static string EditMyProfilePage_Location {
            get {
                return ResourceManager.GetString("EditMyProfilePage_Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 名字: 的本地化字符串。
        /// </summary>
        public static string EditMyProfilePage_Name {
            get {
                return ResourceManager.GetString("EditMyProfilePage_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 你好世界 的本地化字符串。
        /// </summary>
        public static string HelloWorld {
            get {
                return ResourceManager.GetString("HelloWorld", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 首页 的本地化字符串。
        /// </summary>
        public static string HomePage_Home_Header {
            get {
                return ResourceManager.GetString("HomePage_Home_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 提及 的本地化字符串。
        /// </summary>
        public static string HomePage_Mention_Header {
            get {
                return ResourceManager.GetString("HomePage_Mention_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 私信 的本地化字符串。
        /// </summary>
        public static string HomePage_Message_Header {
            get {
                return ResourceManager.GetString("HomePage_Message_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 确定退出嘛? 的本地化字符串。
        /// </summary>
        public static string Msg_ConfirmToExit {
            get {
                return ResourceManager.GetString("Msg_ConfirmToExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 对话 的本地化字符串。
        /// </summary>
        public static string NewMessagePage_Header {
            get {
                return ResourceManager.GetString("NewMessagePage_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 与{0}的对话 的本地化字符串。
        /// </summary>
        public static string NewMessagePage_Header_ChatWithUser {
            get {
                return ResourceManager.GetString("NewMessagePage_Header_ChatWithUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用户名格式不正确 的本地化字符串。
        /// </summary>
        public static string NewMessagePage_Header_NotAValidUserName {
            get {
                return ResourceManager.GetString("NewMessagePage_Header_NotAValidUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0}没有关注你 的本地化字符串。
        /// </summary>
        public static string NewMessagePage_Header_UserNotFollowYou {
            get {
                return ResourceManager.GetString("NewMessagePage_Header_UserNotFollowYou", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 提到: {0} 的本地化字符串。
        /// </summary>
        public static string NewTweetPage_Header_Mention {
            get {
                return ResourceManager.GetString("NewTweetPage_Header_Mention", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 引用: 的本地化字符串。
        /// </summary>
        public static string NewTweetPage_Header_Quote {
            get {
                return ResourceManager.GetString("NewTweetPage_Header_Quote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 回复: {0} 的本地化字符串。
        /// </summary>
        public static string NewTweetPage_Header_ReplyTo {
            get {
                return ResourceManager.GetString("NewTweetPage_Header_ReplyTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 怎么啦? 的本地化字符串。
        /// </summary>
        public static string NewTweetPage_Header_WhatsHappening {
            get {
                return ResourceManager.GetString("NewTweetPage_Header_WhatsHappening", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 收藏 的本地化字符串。
        /// </summary>
        public static string ProfilePage_Favorites_Header {
            get {
                return ResourceManager.GetString("ProfilePage_Favorites_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 关注者 的本地化字符串。
        /// </summary>
        public static string ProfilePage_Followers_Header {
            get {
                return ResourceManager.GetString("ProfilePage_Followers_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 关注 的本地化字符串。
        /// </summary>
        public static string ProfilePage_Following_Header {
            get {
                return ResourceManager.GetString("ProfilePage_Following_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 收藏 的本地化字符串。
        /// </summary>
        public static string ProfilePage_ProfileDetail_Favorites {
            get {
                return ResourceManager.GetString("ProfilePage_ProfileDetail_Favorites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 关注者 的本地化字符串。
        /// </summary>
        public static string ProfilePage_ProfileDetail_Followers {
            get {
                return ResourceManager.GetString("ProfilePage_ProfileDetail_Followers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 正在关注 的本地化字符串。
        /// </summary>
        public static string ProfilePage_ProfileDetail_Following {
            get {
                return ResourceManager.GetString("ProfilePage_ProfileDetail_Following", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 资料 的本地化字符串。
        /// </summary>
        public static string ProfilePage_ProfileDetail_Header {
            get {
                return ResourceManager.GetString("ProfilePage_ProfileDetail_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 推文 的本地化字符串。
        /// </summary>
        public static string ProfilePage_ProfileDetail_Tweets {
            get {
                return ResourceManager.GetString("ProfilePage_ProfileDetail_Tweets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 推文 的本地化字符串。
        /// </summary>
        public static string ProfilePage_Tweets_Header {
            get {
                return ResourceManager.GetString("ProfilePage_Tweets_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 推文 的本地化字符串。
        /// </summary>
        public static string SearchPage_SearchForTweets_Header {
            get {
                return ResourceManager.GetString("SearchPage_SearchForTweets_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用户 的本地化字符串。
        /// </summary>
        public static string SearchPage_SearchForUsers_Header {
            get {
                return ResourceManager.GetString("SearchPage_SearchForUsers_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 关于 的本地化字符串。
        /// </summary>
        public static string SettingsPage_About_Header {
            get {
                return ResourceManager.GetString("SettingsPage_About_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 API信息: 的本地化字符串。
        /// </summary>
        public static string SettingsPage_APIInfo {
            get {
                return ResourceManager.GetString("SettingsPage_APIInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 清空缓存 的本地化字符串。
        /// </summary>
        public static string SettingsPage_ClearCache {
            get {
                return ResourceManager.GetString("SettingsPage_ClearCache", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设置API 的本地化字符串。
        /// </summary>
        public static string SettingsPage_EditAPI {
            get {
                return ResourceManager.GetString("SettingsPage_EditAPI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 常规 的本地化字符串。
        /// </summary>
        public static string SettingsPage_General_Header {
            get {
                return ResourceManager.GetString("SettingsPage_General_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 语言: 的本地化字符串。
        /// </summary>
        public static string SettingsPage_Language {
            get {
                return ResourceManager.GetString("SettingsPage_Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 详情 的本地化字符串。
        /// </summary>
        public static string StatusPage_Detail_Header {
            get {
                return ResourceManager.GetString("StatusPage_Detail_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 转推 的本地化字符串。
        /// </summary>
        public static string StatusPage_Retweets_Header {
            get {
                return ResourceManager.GetString("StatusPage_Retweets_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 收藏 的本地化字符串。
        /// </summary>
        public static string StatusPage_StatusDetail_Favorites {
            get {
                return ResourceManager.GetString("StatusPage_StatusDetail_Favorites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 位置 的本地化字符串。
        /// </summary>
        public static string StatusPage_StatusDetail_Location {
            get {
                return ResourceManager.GetString("StatusPage_StatusDetail_Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 转推 的本地化字符串。
        /// </summary>
        public static string StatusPage_StatusDetail_Retweets {
            get {
                return ResourceManager.GetString("StatusPage_StatusDetail_Retweets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 收藏成功了哟 的本地化字符串。
        /// </summary>
        public static string Toast_Msg_AddFavoriteSuccessfully {
            get {
                return ResourceManager.GetString("Toast_Msg_AddFavoriteSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 删除成功 的本地化字符串。
        /// </summary>
        public static string Toast_Msg_DeleteSuccessfully {
            get {
                return ResourceManager.GetString("Toast_Msg_DeleteSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 关注成功了哟 的本地化字符串。
        /// </summary>
        public static string Toast_Msg_FollowSuccessfully {
            get {
                return ResourceManager.GetString("Toast_Msg_FollowSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 嗨, {0}~ 的本地化字符串。
        /// </summary>
        public static string Toast_Msg_HelloUser {
            get {
                return ResourceManager.GetString("Toast_Msg_HelloUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 私信发送成功了哟 的本地化字符串。
        /// </summary>
        public static string Toast_Msg_MessageSentSuccessfully {
            get {
                return ResourceManager.GetString("Toast_Msg_MessageSentSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 没有更多的门神了 的本地化字符串。
        /// </summary>
        public static string Toast_Msg_NoMoreMentions {
            get {
                return ResourceManager.GetString("Toast_Msg_NoMoreMentions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 没有更多的转推了 的本地化字符串。
        /// </summary>
        public static string Toast_Msg_NoMoreRetweets {
            get {
                return ResourceManager.GetString("Toast_Msg_NoMoreRetweets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 没有更多的推文了 的本地化字符串。
        /// </summary>
        public static string Toast_Msg_NoMoreTweets {
            get {
                return ResourceManager.GetString("Toast_Msg_NoMoreTweets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 还没有新的门神呢 的本地化字符串。
        /// </summary>
        public static string Toast_Msg_NoNewMentions {
            get {
                return ResourceManager.GetString("Toast_Msg_NoNewMentions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 还没有新的转推呢 的本地化字符串。
        /// </summary>
        public static string Toast_Msg_NoNewRetweets {
            get {
                return ResourceManager.GetString("Toast_Msg_NoNewRetweets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 还没有新的推文呢 的本地化字符串。
        /// </summary>
        public static string Toast_Msg_NoNewTweets {
            get {
                return ResourceManager.GetString("Toast_Msg_NoNewTweets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 没有推文搜索结果 的本地化字符串。
        /// </summary>
        public static string Toast_Msg_NoSearchTweetResults {
            get {
                return ResourceManager.GetString("Toast_Msg_NoSearchTweetResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 只有经过{0}确认的关注者才能查看其推文 的本地化字符串。
        /// </summary>
        public static string Toast_Msg_NotFollowPrivateUser {
            get {
                return ResourceManager.GetString("Toast_Msg_NotFollowPrivateUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 不能向没有关注你的{0}发送私信哟 的本地化字符串。
        /// </summary>
        public static string Toast_Msg_NotFollowYou {
            get {
                return ResourceManager.GetString("Toast_Msg_NotFollowYou", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 成功取消收藏 的本地化字符串。
        /// </summary>
        public static string Toast_Msg_RemoveFavoriteSuccessfully {
            get {
                return ResourceManager.GetString("Toast_Msg_RemoveFavoriteSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请求发送成功了哟 的本地化字符串。
        /// </summary>
        public static string Toast_Msg_RequestSentSuccessfully {
            get {
                return ResourceManager.GetString("Toast_Msg_RequestSentSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 转推成功了哟 的本地化字符串。
        /// </summary>
        public static string Toast_Msg_RetweetSuccessfully {
            get {
                return ResourceManager.GetString("Toast_Msg_RetweetSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 推文发送成功了哟 的本地化字符串。
        /// </summary>
        public static string Toast_Msg_TweetSentSuccessfully {
            get {
                return ResourceManager.GetString("Toast_Msg_TweetSentSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 成功取消关注 的本地化字符串。
        /// </summary>
        public static string Toast_Msg_UnfollowSuccessfully {
            get {
                return ResourceManager.GetString("Toast_Msg_UnfollowSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 喔呦, 有不明原因的错误入侵 的本地化字符串。
        /// </summary>
        public static string Toast_Msg_UnknowError {
            get {
                return ResourceManager.GetString("Toast_Msg_UnknowError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 更新成功了哟 的本地化字符串。
        /// </summary>
        public static string Toast_Msg_UpdateMyProfileSuccessfully {
            get {
                return ResourceManager.GetString("Toast_Msg_UpdateMyProfileSuccessfully", resourceCulture);
            }
        }
    }
}
