//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.225
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Chicken.Resources {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Chicken.Resources.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 API类型: 的本地化字符串。
        /// </summary>
        public static string APISettingsPage_APIType {
            get {
                return ResourceManager.GetString("APISettingsPage_APIType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 链接: 的本地化字符串。
        /// </summary>
        public static string APISettingsPage_APIUrl {
            get {
                return ResourceManager.GetString("APISettingsPage_APIUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 API设置 的本地化字符串。
        /// </summary>
        public static string APISettingsPage_Header {
            get {
                return ResourceManager.GetString("APISettingsPage_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 简介: 的本地化字符串。
        /// </summary>
        public static string EditMyProfilePage_Description {
            get {
                return ResourceManager.GetString("EditMyProfilePage_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 编辑个人资料 的本地化字符串。
        /// </summary>
        public static string EditMyProfilePage_Header {
            get {
                return ResourceManager.GetString("EditMyProfilePage_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 链接: 的本地化字符串。
        /// </summary>
        public static string EditMyProfilePage_Link {
            get {
                return ResourceManager.GetString("EditMyProfilePage_Link", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 位置: 的本地化字符串。
        /// </summary>
        public static string EditMyProfilePage_Location {
            get {
                return ResourceManager.GetString("EditMyProfilePage_Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 名字: 的本地化字符串。
        /// </summary>
        public static string EditMyProfilePage_Name {
            get {
                return ResourceManager.GetString("EditMyProfilePage_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 你好世界 的本地化字符串。
        /// </summary>
        public static string HelloWorld {
            get {
                return ResourceManager.GetString("HelloWorld", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 首页 的本地化字符串。
        /// </summary>
        public static string HomePage_Home_Header {
            get {
                return ResourceManager.GetString("HomePage_Home_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 提及 的本地化字符串。
        /// </summary>
        public static string HomePage_Mention_Header {
            get {
                return ResourceManager.GetString("HomePage_Mention_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 私信 的本地化字符串。
        /// </summary>
        public static string HomePage_Message_Header {
            get {
                return ResourceManager.GetString("HomePage_Message_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 对话 的本地化字符串。
        /// </summary>
        public static string NewMessagePage_Header {
            get {
                return ResourceManager.GetString("NewMessagePage_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 与{0}的对话 的本地化字符串。
        /// </summary>
        public static string NewMessagePage_Header_ChatWithUser {
            get {
                return ResourceManager.GetString("NewMessagePage_Header_ChatWithUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用户名格式不正确 的本地化字符串。
        /// </summary>
        public static string NewMessagePage_Header_NotAValidUserName {
            get {
                return ResourceManager.GetString("NewMessagePage_Header_NotAValidUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0}没有关注你 的本地化字符串。
        /// </summary>
        public static string NewMessagePage_Header_UserNotFollowYou {
            get {
                return ResourceManager.GetString("NewMessagePage_Header_UserNotFollowYou", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 提到: {0} 的本地化字符串。
        /// </summary>
        public static string NewTweetPage_Header_Mention {
            get {
                return ResourceManager.GetString("NewTweetPage_Header_Mention", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 引用: 的本地化字符串。
        /// </summary>
        public static string NewTweetPage_Header_Quote {
            get {
                return ResourceManager.GetString("NewTweetPage_Header_Quote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 回复: {0} 的本地化字符串。
        /// </summary>
        public static string NewTweetPage_Header_ReplyTo {
            get {
                return ResourceManager.GetString("NewTweetPage_Header_ReplyTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 怎么啦? 的本地化字符串。
        /// </summary>
        public static string NewTweetPage_Header_WhatsHappening {
            get {
                return ResourceManager.GetString("NewTweetPage_Header_WhatsHappening", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 收藏 的本地化字符串。
        /// </summary>
        public static string ProfilePage_Favorites_Header {
            get {
                return ResourceManager.GetString("ProfilePage_Favorites_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 关注者 的本地化字符串。
        /// </summary>
        public static string ProfilePage_Followers_Header {
            get {
                return ResourceManager.GetString("ProfilePage_Followers_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 正在关注 的本地化字符串。
        /// </summary>
        public static string ProfilePage_Following_Header {
            get {
                return ResourceManager.GetString("ProfilePage_Following_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 资料 的本地化字符串。
        /// </summary>
        public static string ProfilePage_ProfileDetail_Header {
            get {
                return ResourceManager.GetString("ProfilePage_ProfileDetail_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 推文 的本地化字符串。
        /// </summary>
        public static string ProfilePage_Tweets_Header {
            get {
                return ResourceManager.GetString("ProfilePage_Tweets_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 关于 的本地化字符串。
        /// </summary>
        public static string SettingsPage_About_Header {
            get {
                return ResourceManager.GetString("SettingsPage_About_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 API信息: 的本地化字符串。
        /// </summary>
        public static string SettingsPage_APIInfo {
            get {
                return ResourceManager.GetString("SettingsPage_APIInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 清空缓存 的本地化字符串。
        /// </summary>
        public static string SettingsPage_ClearCache {
            get {
                return ResourceManager.GetString("SettingsPage_ClearCache", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设置API 的本地化字符串。
        /// </summary>
        public static string SettingsPage_EditAPI {
            get {
                return ResourceManager.GetString("SettingsPage_EditAPI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 常规 的本地化字符串。
        /// </summary>
        public static string SettingsPage_General_Header {
            get {
                return ResourceManager.GetString("SettingsPage_General_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 语言: 的本地化字符串。
        /// </summary>
        public static string SettingsPage_Language {
            get {
                return ResourceManager.GetString("SettingsPage_Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 详情 的本地化字符串。
        /// </summary>
        public static string StatusPage_Detail_Header {
            get {
                return ResourceManager.GetString("StatusPage_Detail_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 转推 的本地化字符串。
        /// </summary>
        public static string StatusPage_Retweets_Header {
            get {
                return ResourceManager.GetString("StatusPage_Retweets_Header", resourceCulture);
            }
        }
    }
}
